apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod
spec:
  containers:
  - name: data-processor
    image: data-processor

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: Size
            operator: In #NotIn
            values:
            - Large
            - Medium