# Default values for application-1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: new-deployment
  replicaCount: 4
  image:
    name: nginx
    version: latest

service:
  name: new-service
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 32046
